#!/bin/bash

if [ -z $1 ]
then
echo "error = No filename provided"
	exit
elif [ $# -gt 1 ]
then
echo "The script takes only 1 argument i.e. filename"
	exit
elif [ "$1" == "-h" -o "$1" == "--help" ]; then
echo "Usage: `basename $0`
./script <filename> e.g ./script passwd"
  exit 0
fi

fname=$1
if [ -f $fname ]
then
exec < $fname

while read file
do
	cat $fname | cut -d':' -f3 > tmp_sum
done
grep . tmp_sum | paste -sd+ | bc
rm tmp_sum
else
echo "no such file"
	exit
fi
